#pragma once

#define GABAGOOL_SCREEN_W 200
#define GABAGOOL_SCREEN_H 228
#define GABAGOOL_PAN_W 260
#define GABAGOOL_AUDIO_RATE 8000
#define GABAGOOL_AUDIO_SOURCE_RATE 8000
#define GABAGOOL_AUDIO_MAX_UPSAMPLE 1
#define GABAGOOL_IMAGE_COUNT 8
#define GABAGOOL_AUDIO_TRACK_COUNT 3
#define GABAGOOL_MUSIC_TRACK_COUNT 2
#define GABAGOOL_GUBBY_SFX_TRACK_INDEX 1

static const uint32_t GABAGOOL_IMAGE_RESOURCE_IDS[GABAGOOL_IMAGE_COUNT] = {
  RESOURCE_ID_IMAGE_00, RESOURCE_ID_IMAGE_01, RESOURCE_ID_IMAGE_02, RESOURCE_ID_IMAGE_03, RESOURCE_ID_IMAGE_04, RESOURCE_ID_IMAGE_05, RESOURCE_ID_IMAGE_06, RESOURCE_ID_IMAGE_07
};

static const uint16_t GABAGOOL_IMAGE_WIDTHS[GABAGOOL_IMAGE_COUNT] = {
  260, 228, 260, 260, 260, 260, 260, 260
};

// Track 0: gabagooltmeme.ogg
#define GABAGOOL_TRACK_0_CHUNKS 1
static const uint32_t GABAGOOL_TRACK_0_RESOURCE_IDS[GABAGOOL_TRACK_0_CHUNKS] = {
  RESOURCE_ID_AUDIO_00_00
};

// Track 1: gubbysfx.ogg
#define GABAGOOL_TRACK_1_CHUNKS 1
static const uint32_t GABAGOOL_TRACK_1_RESOURCE_IDS[GABAGOOL_TRACK_1_CHUNKS] = {
  RESOURCE_ID_AUDIO_01_00
};

// Track 2: heartkate-helloktty_gubby-this-gubby-that.ogg
#define GABAGOOL_TRACK_2_CHUNKS 3
static const uint32_t GABAGOOL_TRACK_2_RESOURCE_IDS[GABAGOOL_TRACK_2_CHUNKS] = {
  RESOURCE_ID_AUDIO_02_00, RESOURCE_ID_AUDIO_02_01, RESOURCE_ID_AUDIO_02_02
};


typedef struct {
  uint32_t total_samples;
  uint32_t encoded_bytes;
  uint32_t chunk_count;
  const uint32_t *chunk_resource_ids;
} GabagoolAudioTrack;

static const GabagoolAudioTrack GABAGOOL_AUDIO_TRACKS[GABAGOOL_AUDIO_TRACK_COUNT] = {
  { 225286u, 56322u, GABAGOOL_TRACK_0_CHUNKS, GABAGOOL_TRACK_0_RESOURCE_IDS },
  { 3619u, 905u, GABAGOOL_TRACK_1_CHUNKS, GABAGOOL_TRACK_1_RESOURCE_IDS },
  { 696785u, 174197u, GABAGOOL_TRACK_2_CHUNKS, GABAGOOL_TRACK_2_RESOURCE_IDS }
};

static const uint8_t GABAGOOL_MUSIC_TRACK_INDEXES[GABAGOOL_MUSIC_TRACK_COUNT] = {
  0u, 2u
};
